version: 0.2
phases:
  install:
    commands:
      - echo Istalling composer dependencies
      - composer install --no-progress --no-suggest
  build:
    commands:
      - ./vendor/bin/phpunit
  post_build:
    commands:
      - pwd
