version: 0.2
phases:
  build:
    commands:
      - ls -la
      - php --version
  install:
    commands:
      - echo Istalling composer dependencies
      - composer install
  post_build:
    commands:
      - pwd
